FROM php:8.1.8-fpm
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
        php8.0-pgsql \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd
	&& RUN curl -sS https://get.symfony.com/cli/installer | bash
	&& mv /root/.symfony/bin/symfony /usr/local/bin/symfony
WORKDIR /app/public


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer



RUN git config --global user.email "maria.angelica.valderrama@correounivalle.edu.co" \ 
    && git config --global user.name "Angelica"

