version: '3.8'

services:
  php:
    build:
      context: .
      target: app_php
    image: sf-docker/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=localhost
      PHP_IDE_CONFIG: serverName=localhost

    volumes:
      - .:/app:rw,cached
      - ./var:/app/var
  nginx:
    build:
      context: .
      target: app_nginx
    image: sf-docker/nginx:dev
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./public:/app/public:ro
    ports:
      - "8084:80"

volumes:
  db-data:
  var:
