api_create_services:
    path:       api/v1/services
    controller: App\Controller\ServicesController::create
    methods:    POST  


api_get_services:
    path:       api/v1/services
    controller: App\Controller\ServicesController::getServices
    methods:    GET    


