products:
    path: /api/product/{id}
    controller: App\Controller\ProductsController::lowestPrice
    methods:    POST

customers:
    path: /api/customers/lista
    # the controller value has the format 'controller_class::method_name' 
    controller: App\Controller\CustomersController::list
    methods:    POST

